@startmindmap
* 开发计划
** 需求分析
** 设计
*** 概念模型设计（已完成7.12）
*** 表结构设计（7.12）
*** 技术选型和项目搭建（7.13）
** 开发（7.14-7.20）
*** 用户端
**** 登录注册
***** 注册功能/手机号、验证码注册加登录
***** 登录功能：token设置
**** 订单流程
***** 浏览商品
***** 点击商品详情
***** 点击购买商品
***** 支付订单
***** 生成订单
**** 购物车实现
***** 单独的页面陈列用户想购买的商品
***** 用户管理商品
**** 商品评论
***** 点击订单完成后进行商品评论
***** 商品评论显示在商品详情页
**** 商品推荐
***** 记录用户搜索记录
***** 查询类似的商品展示（个人定制）
***** 记录热榜，推荐商品
*** 商家端
**** 商品管理
**** 订单管理
**** 会员管理
**** 注册
**** 权限管理
**** 数据统计
** 测试
@endmindmap